eureka:
  client:
    service-url:
      defauktZone: http://127.0.0.1:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/